name: Deploy with Tag and GH Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'リリースするタグ名（例: v1.2.3）'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write  # GH Release 作成には必要

jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    environment: stg
    outputs:
      tag_name: ${{ steps.set-tag.outputs.tag_name }}
    steps:
      - name: タグ名を環境変数にセット
        id: set-tag
        run: echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: STGデプロイ処理（仮）
        run: echo "Deploying to STG... with tag ${{ github.event.inputs.tag_name }}"

      - name: プレリリースを作成（-pre付きタグ）
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}-pre
          name: STG Release - ${{ github.event.inputs.tag_name }}
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prd:
    needs: deploy-stg
    runs-on: ubuntu-latest
    environment:
      name: prd  # ここで承認フローを有効化
    steps:
      - name: タグ名の確認
        run: echo "Deploying to PRD with tag ${{ github.event.inputs.tag_name }}"

      - name: 本番デプロイ処理（仮）
        run: echo "Deploying to production..."

      - name: 正式リリースを作成
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: Release ${{ github.event.inputs.tag_name }}
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
