name: Deploy with Approval

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Echo STG
        run: echo "Deploying to STG... COMMENT=${{ vars.COMMENT }}"

  deploy-prd:
    needs: deploy-stg
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - name: Echo PRD
        run: echo "Deploying to PRD... COMMENT=${{ vars.COMMENT }}"
