name: Deploy with Approval

on:
  workflow_dispatch:
    branches:
      - main

permissions:
  actions: write

jobs:
  deploy-stg:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Echo STG
        run: echo "Deploying to STG... COMMENT=${{ vars.COMMENT }}"

  deploy-prd:
    if: github.ref == 'refs/heads/main'
    needs: deploy-stg
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - name: Echo PRD
        run: echo "Deploying to PRD... COMMENT=${{ vars.COMMENT }}"
